### PR TITLE
Fix aliasing with path.resolve() issue on windows

### LINKED ISSUE #11: "Could not load F:\tinybear\tinybearLab\rollup\libs/m1"  in windows
config:
`export default {
  entry: 'main.js',
  dest: 'dist/bundle.js',
  format: 'umd',
  plugins: [ 
    alias({
      libs: path.resolve(__dirname, './libs')
    }),
    uglify()
  ],
};`

import code:
`import hello from "libs/m1"
import hi from "libs/m2"`

run :"rollup -c config.js -m inline"

Then, will expose an error:
`Could not load F:\tinybear\tinybearLab\rollup\libs/m1 (imported by F:\tinybear\tinybearLab\roll
up\main.js): ENOENT: no such file or directory, open 'F:\tinybear\tinybearLab\rollup\libs\m1'`

But modify import code  like this:
`import hello from "libs/m1.js"
import hi from "libs/m2.js"`

run the build command will be ok.

### PR DESCRIPTION
**Pull request by mhhegazy**
@Rich-Harris Could you take a look?

### Added 3 test  cases:
- Platform path.resolve('file-without-extension') aliasing
- Windows absolute path aliasing
- Platform path.resolve('file-with.ext') aliasing 

### This fix:
- facebook/react#9350
- facebook/react#9540 [only the part that related to rollup-plugin-alias]
- vuejs/vue#4338

### And Closes #11

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -1,10 +1,11 @@
 import test from 'ava';
-import { posix as path } from 'path';
+import paltformPath, { posix as path } from 'path';
```
Comment (frostney) [inline test/index.js]: Shouldn't this be `platformPath`?

**Comment by frostney** [comment]
I'm not sure `platformPath` is a good export name here to be honest. I would rather prefer `import path, { posix } from 'path'` and change the `path` references to `posix`.

Let know what you think @mhhegazy

**Comment by mhhegazy** [comment]
@frostney I agree this will be more clear

**Comment by mhhegazy** [comment]
@frostney please rerun checks again; it was broken because of resolved issue on appveyor.

we should resolve this issue as soon as possible because it break build of many projects on windows

**Comment by ovirovkin** [comment]
@mhhegazy Is there any reason why this fix cannot be pushed?

**Comment by mhhegazy** [comment]
@ovirovkin do mean merged? I don't know!

I have tested it in cases that used in react and vue and it worked as desired and this only pull request that resolve this problem.

**Comment by mhhegazy** [comment]
@ovirovkin
what issue that bring you here?

is it react build on windows or other issue? 

- if react please check facebook/react#10982
- if other please tell me more about your case

**Comment by ovirovkin** [comment]
@mhhegazy Yes, it's react build on windows issue. I fixed build as you suggested here: [#9540](https://github.com/facebook/react/issues/9540) but it's causing 23 failed tests. So I was wondered can this be merged, to fix an issue properly. I don't know why they are not failing for you, also I have only 1465 tests total and you have 2559 on a screenshots.

**Comment by mhhegazy** [comment]
you can try to clone PR repo (https://github.com/mhhegazy/react.git) and build it and tell me what is the result of build and test.
which tests are failing?

**Comment by Rich-Harris** [comment]
thanks all, LGTM. Will cut a new release soon

**Comment by ovirovkin** [comment]
@mhhegazy Thanks for your help, your branch looks better. But there is still 2 suits are failing. Results:
```
Summary of all failing tests
 FAIL  src\renderers\dom\shared\__tests__\ReactDOMServerIntegration-test.js
  ● Test suite failed to run

    C:\Users\User\Documents\react-test\react\src\renderers\dom\shared\__tests__\ReactDOMServerIntegration-test.js:41
    async function expectErrors(fn, count) {
          ^^^^^^^^

    SyntaxError: Unexpected token function

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:292:17)
      at undefined.next (native)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:787:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)


 FAIL  src\renderers\__tests__\ReactComponent-test.js
  ● Test suite failed to run

    C:\Users\User\Documents\react-test\react\src\renderers\__tests__\ReactComponent-test.js:429
      it('throws if a plain object is used as a child when using SSR', async function () {
                                                                       ^^^^^

    SyntaxError: missing ) after argument list

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:292:17)
      at undefined.next (native)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:787:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by mhhegazy** [comment]
I will take a look at it,
this not related to the build or rollup-plugin-alias so let complete conversation on facebook/react#9540

**Comment by ovirovkin** [comment]
@mhhegazy Thank you, I really appreciate your help.

**Comment by mhhegazy** [comment]
@ovirovkin you are welcome, I'll get into testing in next weekend,
but for now could you approve that build completed successfully here facebook/react#10982
